language: node_js
node_js: stable

sudo: required

cache:
    directories
        - node_modules



install:
   - npm install -D
   - cd ./test/smoke/template
   - npm install -D
   - cd ../../../

script:
   - npm test
   
